$servers = @(
    "c578dtsgrsapp.clrrs.loc",
    "c583ehtgrsapp.clrrs.loc",
    "c583waagrsapp.clrrs.loc",
    "c699jdpgrsapp.clrrs.loc",
    "c701dnagrsapp.clrrs.loc",
    "c705ncagrsapp.clrrs.loc",
    "c711cxbgrsapp.clrrs.loc",
    "c713ncagrsapp.clrrs.loc",
    "c718hucgrsapp.clrrs.loc",
    "c718mqsgrsapp.clrrs.loc",
    "c721wesgrsapp.clrrs.loc",
    "c722awxgrsapp.clrrs.loc",
    "c724ehxgrsapp.clrrs.loc",
    "c725nkegrsapp.clrrs.loc",
    "c728sxhgrsapp.clrrs.loc",
    "c730tmtgrsapp.clrrs.loc",
    "c730wzxgrsapp.clrrs.loc",
    "c732dnegrsapp.clrrs.loc",
    "c736adegrsapp.clrrs.loc",
    "c736fujgrsapp.clrrs.loc",
    "c737pdbgrsapp.clrrs.loc",
    "c738bwxgrsapp.clrrs.loc",
    "c739jnwgrsapp.clrrs.loc",
    "c748kwpgrsapp.clrrs.loc",
    "c750bfygrsapp.clrrs.loc",
    "c750pdbgrsapp.clrrs.loc",
    "c750xmzgrsapp.clrrs.loc",
    "c752bxjgrsapp.clrrs.loc",
    "c759ewkgrsapp.clrrs.loc",
    "c774ppbgrsapp.clrrs.loc",
    "c793xdjfarsrv.clrrs.loc",
    "c810xdcgrsapp.clrrs.loc",
    "c817ypbgrsapp.clrrs.loc",
    "c825xyvgrsapp.clrrs.loc",
    "c829rfdgrsapp.clrrs.loc",
    "c841zgvgrsapp.clrrs.loc",
    "c862dghgrsapp.clrrs.loc",
    "c864wrrgrsapp.clrrs.loc",
    "c870wrrgrsapp.clrrs.loc",
    "c884pukgrsapp.clrrs.loc",
    "c886dsggrsapp.clrrs.loc",
    "c891msxgrsapp.clrrs.loc",
    "c892drrgrsapp.clrrs.loc",
    "c892dzygrsapp.clrrs.loc",
    "c898gswgrsapp.clrrs.loc",
    "c901nzhgrsapp.clrrs.loc",
    "c903gdhgrsapp.clrrs.loc",
    "c904bvfgrsapp.clrrs.loc",
    "c904fjvgrsapp.clrrs.loc",
    "c905thfgrsapp.clrrs.loc",
    "c931yssgrsapp.clrrs.loc",
    "c938xhagrsapp.clrrs.loc",
    "c958xcmgrsapp.clrrs.loc"
)


foreach ($server in $servers | Sort-Object) {
    echo "$server"
    dir "\\$($server)\d$\logfiles\pdfservice_*-log.json" -File | ?{$_.CreationTime -lt (Get-Date).AddDays(-1)} | %{echo "`tRemoving $($_.FullName)"; Remove-Item $_.FullName -Recurse -Force -ErrorAction Continue -whatif}
    echo "`n`n"
}
